labels:
  redis:
    name: redis
  postgres:
    name: postgres
  backend:
    name: backend
  adminBackend:
    name: admin-backend
  consumer:
    name: consumer
  indexer:
    name: indexer

ports:
  redis: 6379
  postgres: 5432
  backend: 8080
  adminBackend: 8082
  consumer: 8081

volumes:
  redis:
    name: redis-data
    class: standard-rwo
    storage: 10Gi
  postgres:
    name: postgres-data
    class: standard-rwo
    storage: 50Gi
  nfts:
    name: nft-data
    claim: nft-volume-claim
    class: standard-rwo
    storage: 50Gi
  factions:
    name: faction-data
    claim: faction-volume-claim
    class: standard-rwo
    storage: 10Gi
  templates:
    name: template-data
    claim: template-volume-claim
    class: standard-rwo
    storage: 50Gi

deployments:
  sha: aabbccdd
  redis:
    replicas: 1
    image: redis
    tag: 7.2.4-alpine
  postgres:
    replicas: 1
    image: postgres
    tag: 14.11-alpine
  backend:
    replicas: 1
    image: brandonjroberts/art-peace-backend
  adminBackend:
    replicas: 1
    image: brandonjroberts/art-peace-backend
  consumer:
    replicas: 1
    image: brandonjroberts/art-peace-consumer
  indexer:
    replicas: 1
    image: brandonjroberts/art-peace-indexer

postgres:
  db: art-peace-db
  user: art-peace-user
  password: ArtPeacePassword1234

apibara:
  #streamUrl: https://mainnet.starknet.a5a.ch
  streamUrl: https://sepolia.starknet.a5a.ch
  indexerId: art-peace-indexer-id
  authToken: dna_aabbcc

contracts:
  artPeace: 0x078f4e772300472a68a19f2b1aedbcb7cf2acd6f67a2236372310a528c7eaa67
  usernameStore: 0x051cf8214d781f5ee503cb668505e58f0374bfd602145560ba1b897eb98f2e1a
  nft: 0x03f169f36006f9007b94a7046944d0c351a7a301aae692c995fec41bb38693e8
  host: "07C313Ea8b45044c2272B77eC7332B65bdFef089c4De0FFfaB3De3FD6b85d124"
  end: "1727483400"
